replace tput with stty and cut with pure bash func

diff --git a/tsp b/tsp
--- a/tsp
+++ b/tsp
@@ -1,16 +1,5 @@
 #!/usr/bin/env bash
 
-# ensure we are called interactively
-if [[ ! -t 1 ]]; then
-    echo '[error] stdout must be a terminal. Run game in interactive mode'
-    exit 1
-fi
-
-# TODO: replace with ASCII seq
-if ! tput cup 0 0 2>/dev/null; then
-    echo '[error] tput is not installed. Please, install it with available package manager'
-    exit 1
-fi
 
 # gameplay calculation variables
 ## total mass of the carrier
@@ -37,7 +26,7 @@ G_V=0
 G_h=0
 
 active_mode() {
-    local mode=$(get_shared | cut -d '|' -f 1)
+    local mode=$(get_shared | split '|' 0)
     case "$((mode % 2))" in
         0) echo -n 'menu';;
         1 | -1) echo -n 'gameplay';;
@@ -45,7 +34,7 @@ active_mode() {
 }
 
 active_button() {
-    local active_btn=$(get_shared | cut -d '|' -f 2)
+    local active_btn=$(get_shared | split '|' 1)
     case "$((active_btn % 2))" in
         0) echo -n 'start';;
         1 | -1) echo -n 'select';;
@@ -54,7 +43,7 @@ active_button() {
 
 active_carrier() {
     local length=${#CARRIERS[@]}
-    local active_carr=$(get_shared | cut -d '|' -f 3)
+    local active_carr=$(get_shared | split '|' 2)
     active_carr=${active_carr#-}
     local index=$((active_carr % length))
     echo "${CARRIERS[$index]}"
@@ -62,7 +51,7 @@ active_carrier() {
 
 # shared memory
 write_shared() {
-    echo "$MODE|$ACTIVE_BUTTON|$ACTIVE_CARRIER|$COLS|$LINES" > "$SHM"
+    echo "${MODE:-0}|${ACTIVE_BUTTON:-0}|${ACTIVE_CARRIER:-0}|${COLS:-0}|${LINES:-0}" > "$SHM"
 }
 
 get_shared() {
@@ -73,7 +62,7 @@ get_shared() {
 }
 
 write_commands() {
-    echo "$UPDATE_MENU|$UPDATE_BUTTONS|$UPDATE_CARRIER" > $CPIPE &
+    echo "${UPDATE_MENU:-0}|${UPDATE_BUTTONS:-0}|${UPDATE_CARRIER:-0}" > $CPIPE &
 }
 
 read_commands() {
@@ -82,7 +71,7 @@ read_commands() {
 
 # calculations
 orbit_calc() {
-    while true; do
+    while :; do
         if [[ "$(active_mode)" == 'gameplay' ]]; then
             return 0
         fi
@@ -105,11 +94,8 @@ render_buttons() {
 
     local start_esc=
     local select_esc=
-    if [[ $(active_button) == 'start' ]]; then
-        start_esc="${ESC}[48;5;255m${ESC}[38;5;243m${ESC}[1m"
-    else
-        select_esc="${ESC}[48;5;255m${ESC}[38;5;243m${ESC}[1m"
-    fi
+    [[ $(active_button) == 'start' ]] && start_esc="${ESC}[48;5;255m${ESC}[38;5;243m${ESC}[1m" \
+    || select_esc="${ESC}[48;5;255m${ESC}[38;5;243m${ESC}[1m"
 
     tput cup "$start_button_line" "$start_button_col"
     printf "%s%s${ESC}[0m" "$start_esc" "$START_BUTTON"
@@ -134,42 +120,43 @@ render_carriers() {
 
 render_menu() {
     local comm=$(read_commands)
-    local u_menu=$(echo "$comm"| cut -d '|' -f 1)
-    local u_buttons=$(echo "$comm"| cut -d '|' -f 2)
-    local u_carriers=$(echo "$comm"| cut -d '|' -f 3)
+    local u_menu=$(echo "$comm"| split '|' 0)
+    local u_buttons=$(echo "$comm"| split '|' 1)
+    local u_carriers=$(echo "$comm"| split '|' 2)
 
     local shared=$(get_shared)
     if [[ -z $shared ]]; then
         return 0
     fi
 
-    local cols=$(echo "$shared" | cut -d '|' -f 4)
-    local lines=$(echo "$shared" | cut -d '|' -f 5)
+    local theCols=$(echo "$shared" | split '|' 3)
+    local theLines=$(echo "$shared" | split '|' 4)
 
-    if [[ -n $u_menu ]]; then
+    if (( $u_menu )); then
+        echo u_menu >> debug5
         clear
-        local logo_line=$((lines / 6))
-        local logo_indent=$(calc_d "$cols / 3.77")
+        local logo_line=$((theLines / 6))
+        local logo_indent=$(calc_d "$theCols / 3.77")
         tput cup "$logo_line" 0
         local l=$LOGO
         l=${l//<l>/$(repeat $logo_indent ' ')}
         printf "$l"
 
-        tput cup $(calc_d "$lines / 1.1") 0
+        tput cup $(calc_d "$theLines / 1.1") 0
         local f=$SURFACE_BLOCK
-        f=${f//<b1>/$(repeat $cols '_')}
-        f=${f//<b2>/$(repeat $cols '/')}
+        f=${f//<b1>/$(repeat $theCols '_')}
+        f=${f//<b2>/$(repeat $theCols '/')}
 
         printf "$f"
     fi
 
-    if [[ -n $u_buttons ]]; then
-        render_buttons $(calc_d "$lines / 2.6") $(calc_d "$cols / 2.35")
+    if (( $u_buttons )); then
+        render_buttons $(calc_d "$theLines / 2.6") $(calc_d "$theCols / 2.35")
     fi
 
-    if [[ -n $u_carriers ]]; then
-        local carrier_indent=$(calc_d "$cols / 2.2")
-        local carrier_line=$(calc_d "$lines / 1.5")
+    if (( $u_carriers )); then
+        local carrier_indent=$(calc_d "$theCols / 2.2")
+        local carrier_line=$(calc_d "$theLines / 1.5")
         render_carriers "$carrier_line" "$carrier_indent"
     fi
 
@@ -182,8 +169,8 @@ render_gameplay() {
         return 0
     fi
 
-    local cols=$(echo "$shared" | cut -d '|' -f 4)
-    local lines=$(echo "$shared" | cut -d '|' -f 5)
+    local cols=$(echo "$shared" | split '|' 3)
+    local lines=$(echo "$shared" | split '|' 4)
 
     # show surface if we need
     local surface_height=$(calc_d "$lines - ($lines / 1.1)")
@@ -194,13 +181,10 @@ render_gameplay() {
         f=${f//<b2>/$(repeat $cols '/')}
         printf "$f"
     fi
-
-
-
 }
 
 render() {
-    while true; do
+    while :; do
         case "$(active_mode)" in
             menu) render_menu;;
             gameplay) render_gameplay;;
@@ -209,6 +193,14 @@ render() {
 }
 
 main() {
+    # ensure we are called interactively
+    if [[ ! -t 1 ]]; then
+        echo '[error] stdout must be a terminal. Run game in interactive mode'
+        exit 1
+    fi
+    
+    tput cup 0 0 2>/dev/null
+
     # configure terminal for drawing
     trap cleanup exit
     printf "${ESC}[?1049h"
@@ -222,21 +214,21 @@ main() {
 
     write_commands
 
-    while true; do
+    while :; do
         UPDATE_MENU=
         UPDATE_BUTTONS=
         UPDATE_CARRIER=
 
-        local cols=$(tput cols)
-        if (( cols != COLS )); then
+        local theCols=$(cols)
+        if (( theCols != COLS )); then
             UPDATE_MENU=1
-            COLS=$cols
+            COLS=$theCols
         fi
 
-        local lines=$(tput lines)
-        if (( lines != LINES )); then
+        local theLines=$(lines)
+        if (( theLines != LINES )); then
             UPDATE_MENU=1
-            LINES=$lines
+            LINES=$theLines
         fi
 
         local input=
@@ -330,6 +322,7 @@ calc_d() {
     awk "BEGIN {printf \"%d\n\", $expr }"
 }
 
+# reference: https://github.com/bahamas10/bash-tput
 tput() {
 	local opt OPTIND OPTARG
 	while getopts 'ST:V' opt; do
@@ -371,9 +364,24 @@ tput() {
 	esac
 }
 
+# reference: https://github.com/dylanaraps/pure-bash-bible?tab=readme-ov-file#split-a-string-on-a-delimiter
+split() {
+  data=$(</dev/stdin)
+  IFS=$'\n' read -d "" -ra arr <<< "${data//$1/$'\n'}"
+  printf '%s\n' "${arr[$2]}"
+}
+
+lines() {
+  stty size | split ' ' 0
+}
+
+cols() {
+  stty size | split ' ' 1
+}
+
 # terminal constants
-COLS=$(tput cols)
-LINES=$(tput lines)
+COLS=$(cols)
+LINS=$(lines)
 ESC=$'\x1b'
 SHMID=$(cat /dev/urandom | LC_ALL=C tr -dc 'a-zA-Z0-9' | head -c 64; echo)
 SHM=$([[ "$(uname -s)" == 'Darwin' ]] && echo "/tmp/$SHMID" || echo "/dev/shm/$SHMID")
